version: '3'

services:
  web:
    image: ibbathon/wasp
    env_file: ../secrets/wasp/prod
    environment:
      RAILS_ENV: production
    ports:
      - "80:80"
    working_dir: /wasp

  db:
    env_file: ../secrets/wasp/mysql.prod
