version: '3'

volumes:
  data:

services:
  web:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - data:/var/lib/mysql
